
        go-version: [1.18.x, 1.22.x, 1.23.x]
        platform: [ubuntu-20.2.04, ubuntu-24.04, windows-latest, macos-13, 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: p-go@v5
      with:
        go-version: ${{ matrix.go-version }}
   top-level go.sum needed for
        # the cache key, and specifying multiple go.sums is not trivial
        # (see https://github.com/moby/sys/pull/160 for details).
        cache:ion == '1.18.x' }}
      run: |
        # This corresponds with the list in Makefile:1, but omits the "userns"
        # and "capability" modules, which require go1.21 as minimum.
        echo 'PACKAGES=mountinfo mount sequential signal symlink user' >> $GITHUB_ENV
    - name: go mod tidy
 ux' }}
      run: make cross
    - name: Test
      run: |
        uname -a
        make test

  codespell:
    runs-on: ubuntu-24.04
    steps:
    ackages codespell==v2.3.0
    - run: codespell
